//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DarkMode_2.i18n {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Languages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Languages() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DarkMode_2.i18n.Languages", typeof(Languages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 作者 的本地化字符串。
        /// </summary>
        public static string AboutPage_Author {
            get {
                return ResourceManager.GetString("AboutPage_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DarkMode 更改渠道 的本地化字符串。
        /// </summary>
        public static string AboutPage_ChangeChannel {
            get {
                return ResourceManager.GetString("AboutPage_ChangeChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取 DarkMode 其他渠道版本 的本地化字符串。
        /// </summary>
        public static string AboutPage_ChangeChannelSubtitle {
            get {
                return ResourceManager.GetString("AboutPage_ChangeChannelSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 渠道 的本地化字符串。
        /// </summary>
        public static string AboutPage_Channel {
            get {
                return ResourceManager.GetString("AboutPage_Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查更新 的本地化字符串。
        /// </summary>
        public static string AboutPage_CheckUpdate {
            get {
                return ResourceManager.GetString("AboutPage_CheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 贡献者 的本地化字符串。
        /// </summary>
        public static string AboutPage_Contributor {
            get {
                return ResourceManager.GetString("AboutPage_Contributor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参与了 DarkMode 代码贡献的 GitHub 用户 的本地化字符串。
        /// </summary>
        public static string AboutPage_ContributorSubtitle {
            get {
                return ResourceManager.GetString("AboutPage_ContributorSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版权 的本地化字符串。
        /// </summary>
        public static string AboutPage_Copyright {
            get {
                return ResourceManager.GetString("AboutPage_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DarkMode 信息 的本地化字符串。
        /// </summary>
        public static string AboutPage_DarkModeInfo {
            get {
                return ResourceManager.GetString("AboutPage_DarkModeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包含版本信息等内容 的本地化字符串。
        /// </summary>
        public static string AboutPage_DarkModeInfoSubtitle {
            get {
                return ResourceManager.GetString("AboutPage_DarkModeInfoSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开发者 的本地化字符串。
        /// </summary>
        public static string AboutPage_Developer {
            get {
                return ResourceManager.GetString("AboutPage_Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前往 DarkMode 的 Gitee 首页 的本地化字符串。
        /// </summary>
        public static string AboutPage_Gitee {
            get {
                return ResourceManager.GetString("AboutPage_Gitee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前往 DarkMode 的 GitHub 首页 的本地化字符串。
        /// </summary>
        public static string AboutPage_Github {
            get {
                return ResourceManager.GetString("AboutPage_Github", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助中心 的本地化字符串。
        /// </summary>
        public static string AboutPage_HelpCenter {
            get {
                return ResourceManager.GetString("AboutPage_HelpCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击进入 DarkMode 讨论区获取帮助 的本地化字符串。
        /// </summary>
        public static string AboutPage_HelpCenterSubtitle {
            get {
                return ResourceManager.GetString("AboutPage_HelpCenterSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 许可 的本地化字符串。
        /// </summary>
        public static string AboutPage_License {
            get {
                return ResourceManager.GetString("AboutPage_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        public static string AboutPage_Name {
            get {
                return ResourceManager.GetString("AboutPage_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开放源代码许可 的本地化字符串。
        /// </summary>
        public static string AboutPage_OpenSourceLicense {
            get {
                return ResourceManager.GetString("AboutPage_OpenSourceLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DarkMode 使用的第三方开源库 的本地化字符串。
        /// </summary>
        public static string AboutPage_OpenSourceLicenseSubtitle {
            get {
                return ResourceManager.GetString("AboutPage_OpenSourceLicenseSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐私政策 的本地化字符串。
        /// </summary>
        public static string AboutPage_PrivacyPolicy {
            get {
                return ResourceManager.GetString("AboutPage_PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非常感谢您使用DarkMode。我们非常重视用户隐私和信息安全问题。
        ///
        ///为了更好地保护您的个人信息，我们编写了下面的隐私政策：
        ///1. 本软件承诺严格遵守法律法规和用户隐私保护原则，不会通过网络泄露用户隐私数据。
        ///2. 本软件拥有管理员权限，但不会滥用此权限恶意破坏用户数据。
        ///3. 本软件的日出日落模式等相关功能需要联网进行定位。使用这些功能前请确保您已同意并授权本软件获得您的定位信息。
        ///4. 本软件联网还用来向开发者汇报版本号等信息用于数据统计（如用户数量、各渠道占比等）。我们承诺不会以任何形式泄露用户的个人信息。
        ///5. 本软件会收集必要的用户信息，例如设备信息、网络信息、错误日志等，以便改善软件性能和用户体验。我们承诺不会将这些信息用于非法用途或泄露给第三方。
        ///6. 在特定情况下，为了保护用户权益和遵守法律法规，本软件有可能会披露用户的信息。例如，当政府机关或司法机构正式要求时，或者为了保护本软件、其他用户或社会公共利益时。
        ///7. 用户有权随时联系开发者删除其个人信息。如果您对隐私政策有任何疑问、申诉或投诉，可以通过我们提供的联系方式与开发者取得联系。我们将竭尽所能为您解决问题，保护您的个 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string AboutPage_PrivacyPolicyContent {
            get {
                return ResourceManager.GetString("AboutPage_PrivacyPolicyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DarkMode 对于一些行为的说明 的本地化字符串。
        /// </summary>
        public static string AboutPage_PrivacyPolicySubtitle {
            get {
                return ResourceManager.GetString("AboutPage_PrivacyPolicySubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 鸣谢 的本地化字符串。
        /// </summary>
        public static string AboutPage_Thank {
            get {
                return ResourceManager.GetString("AboutPage_Thank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 为 DarkMode 发展作出贡献，值得展示的用户或团体 的本地化字符串。
        /// </summary>
        public static string AboutPage_ThankSubtitle {
            get {
                return ResourceManager.GetString("AboutPage_ThankSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本 的本地化字符串。
        /// </summary>
        public static string AboutPage_Version {
            get {
                return ResourceManager.GetString("AboutPage_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DarkMode 设置中心 的本地化字符串。
        /// </summary>
        public static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string Dialog_LeftButtonText {
            get {
                return ResourceManager.GetString("Dialog_LeftButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Dialog_RightButtonText {
            get {
                return ResourceManager.GetString("Dialog_RightButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 深色时 的本地化字符串。
        /// </summary>
        public static string DIYPage_Dark {
            get {
                return ResourceManager.GetString("DIYPage_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浅色时 的本地化字符串。
        /// </summary>
        public static string DIYPage_Light {
            get {
                return ResourceManager.GetString("DIYPage_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统光标 的本地化字符串。
        /// </summary>
        public static string DIYPage_Scosor {
            get {
                return ResourceManager.GetString("DIYPage_Scosor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置后自动切换主题时，系统光标也会切换 的本地化字符串。
        /// </summary>
        public static string DIYPage_ScosorSubtitle {
            get {
                return ResourceManager.GetString("DIYPage_ScosorSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 触摸键盘主题色 的本地化字符串。
        /// </summary>
        public static string DIYPage_ScreenKeyboard {
            get {
                return ResourceManager.GetString("DIYPage_ScreenKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开启后触摸键盘将跟随系统主题色 的本地化字符串。
        /// </summary>
        public static string DIYPage_ScreenKeyboardSubtitle {
            get {
                return ResourceManager.GetString("DIYPage_ScreenKeyboardSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 抱歉，本程序仅支持Windows10/11的操作系统。\n你的操作系统版本是： 的本地化字符串。
        /// </summary>
        public static string MainWindow_Tip1 {
            get {
                return ResourceManager.GetString("MainWindow_Tip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法提供服务 的本地化字符串。
        /// </summary>
        public static string MainWindow_Tip2 {
            get {
                return ResourceManager.GetString("MainWindow_Tip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ctrl+Alt+D 快捷键被占用，将无法通过快捷键打开设置，请勿在设置中关闭托盘栏图标，如果意外关闭，请进入 DarkMode 的 GitHub 仓库的 Discussions 页面查看帮助。 的本地化字符串。
        /// </summary>
        public static string MainWindow_Tip3 {
            get {
                return ResourceManager.GetString("MainWindow_Tip3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DarkMode：快捷键被占用 的本地化字符串。
        /// </summary>
        public static string MainWindow_Tip4 {
            get {
                return ResourceManager.GetString("MainWindow_Tip4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法完成的操作 的本地化字符串。
        /// </summary>
        public static string MainWindow_Tip5 {
            get {
                return ResourceManager.GetString("MainWindow_Tip5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取设备定位异常，自动更新日出日落时间功能无法使用。 的本地化字符串。
        /// </summary>
        public static string MainWindow_Tip6 {
            get {
                return ResourceManager.GetString("MainWindow_Tip6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DarkMode 通知 的本地化字符串。
        /// </summary>
        public static string MainWindow_Tip7 {
            get {
                return ResourceManager.GetString("MainWindow_Tip7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DarkMode 运行中，配置请点击 DarkMode 图标 的本地化字符串。
        /// </summary>
        public static string MainWindow_Tip8 {
            get {
                return ResourceManager.GetString("MainWindow_Tip8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string MessageBox_Tip1 {
            get {
                return ResourceManager.GetString("MessageBox_Tip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string MessageBox_Tip2 {
            get {
                return ResourceManager.GetString("MessageBox_Tip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制 的本地化字符串。
        /// </summary>
        public static string MessageBox_Tip3 {
            get {
                return ResourceManager.GetString("MessageBox_Tip3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏模式(实验性功能) 的本地化字符串。
        /// </summary>
        public static string MorePage_GameMode {
            get {
                return ResourceManager.GetString("MorePage_GameMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开启后软件检测到玩游戏时将不会切换主题 的本地化字符串。
        /// </summary>
        public static string MorePage_GameModeSubtitle {
            get {
                return ResourceManager.GetString("MorePage_GameModeSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 GPU 占用率阈值，到达多少时开启 的本地化字符串。
        /// </summary>
        public static string MorePage_GameModeTip {
            get {
                return ResourceManager.GetString("MorePage_GameModeTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string MorePage_Save {
            get {
                return ResourceManager.GetString("MorePage_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实验性功能将在测试成功后在自定义组中上线，随时存在删除的可能性。 的本地化字符串。
        /// </summary>
        public static string MorePage_Tips {
            get {
                return ResourceManager.GetString("MorePage_Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        public static string Navbar_About {
            get {
                return ResourceManager.GetString("Navbar_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义 的本地化字符串。
        /// </summary>
        public static string Navbar_custom {
            get {
                return ResourceManager.GetString("Navbar_custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实验室 的本地化字符串。
        /// </summary>
        public static string Navbar_Laboratory {
            get {
                return ResourceManager.GetString("Navbar_Laboratory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string Navbar_Settings {
            get {
                return ResourceManager.GetString("Navbar_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间 的本地化字符串。
        /// </summary>
        public static string Navbar_Time {
            get {
                return ResourceManager.GetString("Navbar_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 壁纸 的本地化字符串。
        /// </summary>
        public static string Navbar_Wallpaper {
            get {
                return ResourceManager.GetString("Navbar_Wallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        public static string NotifyMenu_Exit {
            get {
                return ResourceManager.GetString("NotifyMenu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string NotifyMenu_Settings {
            get {
                return ResourceManager.GetString("NotifyMenu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该功能暂未开放 的本地化字符串。
        /// </summary>
        public static string SetAboutPage_Tip1 {
            get {
                return ResourceManager.GetString("SetAboutPage_Tip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        public static string SetAboutPage_Tip2 {
            get {
                return ResourceManager.GetString("SetAboutPage_Tip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 跟随系统 的本地化字符串。
        /// </summary>
        public static string SetSettingPage_Tip1 {
            get {
                return ResourceManager.GetString("SetSettingPage_Tip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下次启动时生效 的本地化字符串。
        /// </summary>
        public static string SetSettingPage_Tip10 {
            get {
                return ResourceManager.GetString("SetSettingPage_Tip10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        public static string SetSettingPage_Tip11 {
            get {
                return ResourceManager.GetString("SetSettingPage_Tip11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浅色 的本地化字符串。
        /// </summary>
        public static string SetSettingPage_Tip2 {
            get {
                return ResourceManager.GetString("SetSettingPage_Tip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 深色 的本地化字符串。
        /// </summary>
        public static string SetSettingPage_Tip3 {
            get {
                return ResourceManager.GetString("SetSettingPage_Tip3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动 的本地化字符串。
        /// </summary>
        public static string SetSettingPage_Tip4 {
            get {
                return ResourceManager.GetString("SetSettingPage_Tip4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GitHub 渠道 的本地化字符串。
        /// </summary>
        public static string SetSettingPage_Tip5 {
            get {
                return ResourceManager.GetString("SetSettingPage_Tip5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gitee 渠道 的本地化字符串。
        /// </summary>
        public static string SetSettingPage_Tip6 {
            get {
                return ResourceManager.GetString("SetSettingPage_Tip6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该功能暂不可用 的本地化字符串。
        /// </summary>
        public static string SetSettingPage_Tip7 {
            get {
                return ResourceManager.GetString("SetSettingPage_Tip7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误发生 的本地化字符串。
        /// </summary>
        public static string SetSettingPage_Tip8 {
            get {
                return ResourceManager.GetString("SetSettingPage_Tip8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下次启动时生效，关闭托盘栏图标后可以使用 Ctrl+Alt+D 来快速打开设置中心 的本地化字符串。
        /// </summary>
        public static string SetSettingPage_Tip9 {
            get {
                return ResourceManager.GetString("SetSettingPage_Tip9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否允许 DarkMode 访问你的精确位置 的本地化字符串。
        /// </summary>
        public static string SetTimesPage_Tip1 {
            get {
                return ResourceManager.GetString("SetTimesPage_Tip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \nDarkMode 使用 Windows 位置服务获取设备所在地的地理位置，并计算出日出日落时间。 的本地化字符串。
        /// </summary>
        public static string SetTimesPage_Tip2 {
            get {
                return ResourceManager.GetString("SetTimesPage_Tip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法完成的操作 的本地化字符串。
        /// </summary>
        public static string SetTimesPage_Tip3 {
            get {
                return ResourceManager.GetString("SetTimesPage_Tip3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取设备定位异常，请检查系统定位服务是否开启，或者检查系统代理功能。 的本地化字符串。
        /// </summary>
        public static string SetTimesPage_Tip4 {
            get {
                return ResourceManager.GetString("SetTimesPage_Tip4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        public static string SetTimesPage_Tip5 {
            get {
                return ResourceManager.GetString("SetTimesPage_Tip5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你的设备不存在感光元件，无法使用此功能。 的本地化字符串。
        /// </summary>
        public static string SetTimesPage_Tip6 {
            get {
                return ResourceManager.GetString("SetTimesPage_Tip6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开发者模式 的本地化字符串。
        /// </summary>
        public static string SettingPage_DeveloperMode {
            get {
                return ResourceManager.GetString("SettingPage_DeveloperMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动更新日出日落时间 的本地化字符串。
        /// </summary>
        public static string SettingsPage_AutoSunRiseTime {
            get {
                return ResourceManager.GetString("SettingsPage_AutoSunRiseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开启后软件将每次启动软件时自动更新一次日出日落时间 的本地化字符串。
        /// </summary>
        public static string SettingsPage_AutoSunRiseTimeSubtitle {
            get {
                return ResourceManager.GetString("SettingsPage_AutoSunRiseTimeSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动更新 的本地化字符串。
        /// </summary>
        public static string SettingsPage_AutoUpdate {
            get {
                return ResourceManager.GetString("SettingsPage_AutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开启后软件将自动检测更新 的本地化字符串。
        /// </summary>
        public static string SettingsPage_AutoUpdateSubtitle {
            get {
                return ResourceManager.GetString("SettingsPage_AutoUpdateSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主题色 的本地化字符串。
        /// </summary>
        public static string SettingsPage_Color {
            get {
                return ResourceManager.GetString("SettingsPage_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换软件的主题色 的本地化字符串。
        /// </summary>
        public static string SettingsPage_ColorSubtitle {
            get {
                return ResourceManager.GetString("SettingsPage_ColorSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开发者模式 的本地化字符串。
        /// </summary>
        public static string SettingsPage_DeveloperMode {
            get {
                return ResourceManager.GetString("SettingsPage_DeveloperMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开发者模式，非开发人员请勿进入 的本地化字符串。
        /// </summary>
        public static string SettingsPage_DeveloperModeSubtitle {
            get {
                return ResourceManager.GetString("SettingsPage_DeveloperModeSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言 的本地化字符串。
        /// </summary>
        public static string SettingsPage_Language {
            get {
                return ResourceManager.GetString("SettingsPage_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换软件显示的语言 的本地化字符串。
        /// </summary>
        public static string SettingsPage_LanguageSubtitle {
            get {
                return ResourceManager.GetString("SettingsPage_LanguageSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消息通知 的本地化字符串。
        /// </summary>
        public static string SettingsPage_Notification {
            get {
                return ResourceManager.GetString("SettingsPage_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开启后软件启动时将发送一条通知 的本地化字符串。
        /// </summary>
        public static string SettingsPage_NotificationSubtitle {
            get {
                return ResourceManager.GetString("SettingsPage_NotificationSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置用户配置 的本地化字符串。
        /// </summary>
        public static string SettingsPage_Reset {
            get {
                return ResourceManager.GetString("SettingsPage_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开机自启 的本地化字符串。
        /// </summary>
        public static string SettingsPage_RunStartUp {
            get {
                return ResourceManager.GetString("SettingsPage_RunStartUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开启后软件将在下次启动电脑时自动运行 的本地化字符串。
        /// </summary>
        public static string SettingsPage_RunStartUpSubtitle {
            get {
                return ResourceManager.GetString("SettingsPage_RunStartUpSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 托盘栏图标 的本地化字符串。
        /// </summary>
        public static string SettingsPage_TrayBarIcon {
            get {
                return ResourceManager.GetString("SettingsPage_TrayBarIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开启后软件启动时在托盘栏区域创建软件图标(建议开启) 的本地化字符串。
        /// </summary>
        public static string SettingsPage_TrayBarIconSubtitle {
            get {
                return ResourceManager.GetString("SettingsPage_TrayBarIconSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新渠道 的本地化字符串。
        /// </summary>
        public static string SettingsPage_UpdateChannel {
            get {
                return ResourceManager.GetString("SettingsPage_UpdateChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置检查更新或自动更新的渠道 的本地化字符串。
        /// </summary>
        public static string SettingsPage_UpdateChannelSubtitle {
            get {
                return ResourceManager.GetString("SettingsPage_UpdateChannelSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择壁纸图片 的本地化字符串。
        /// </summary>
        public static string SetWallpaperPage_Tip1 {
            get {
                return ResourceManager.GetString("SetWallpaperPage_Tip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片文件|*.jpg;*.jpeg;*.bmp;*.dib;*.png;*.jfif;*.jpe;*.gif;*.tif;*.tiff;*.wdp;*.heic;*.heif;*.heics;*.heifs;*.hif;*.avci;*.avcs;*.avif;*.avifs 的本地化字符串。
        /// </summary>
        public static string SetWallpaperPage_Tip2 {
            get {
                return ResourceManager.GetString("SetWallpaperPage_Tip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择 JSON 文件 的本地化字符串。
        /// </summary>
        public static string SetWallpaperPage_Tip3 {
            get {
                return ResourceManager.GetString("SetWallpaperPage_Tip3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 json 文件|*.json; 的本地化字符串。
        /// </summary>
        public static string SetWallpaperPage_Tip4 {
            get {
                return ResourceManager.GetString("SetWallpaperPage_Tip4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        public static string SetWallpaperPage_Tip5 {
            get {
                return ResourceManager.GetString("SetWallpaperPage_Tip5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动搜索路径失败，请手动选择。 的本地化字符串。
        /// </summary>
        public static string SetWallpaperPage_Tip6 {
            get {
                return ResourceManager.GetString("SetWallpaperPage_Tip6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择 wallpaper64.exe 文件 的本地化字符串。
        /// </summary>
        public static string SetWallpaperPage_Tip7 {
            get {
                return ResourceManager.GetString("SetWallpaperPage_Tip7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 exe文件|wallpaper64.exe; 的本地化字符串。
        /// </summary>
        public static string SetWallpaperPage_Tip8 {
            get {
                return ResourceManager.GetString("SetWallpaperPage_Tip8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义时间 的本地化字符串。
        /// </summary>
        public static string TimePage_CustomTime {
            get {
                return ResourceManager.GetString("TimePage_CustomTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手动设置颜色模式开始的时间 的本地化字符串。
        /// </summary>
        public static string TimePage_CustomTimeSubtitle {
            get {
                return ResourceManager.GetString("TimePage_CustomTimeSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 深色模式： 的本地化字符串。
        /// </summary>
        public static string TimePage_DarkMode {
            get {
                return ResourceManager.GetString("TimePage_DarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时 的本地化字符串。
        /// </summary>
        public static string TimePage_Hour {
            get {
                return ResourceManager.GetString("TimePage_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 纬度： 的本地化字符串。
        /// </summary>
        public static string TimePage_Latitude {
            get {
                return ResourceManager.GetString("TimePage_Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浅色模式： 的本地化字符串。
        /// </summary>
        public static string TimePage_LightMode {
            get {
                return ResourceManager.GetString("TimePage_LightMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 经度： 的本地化字符串。
        /// </summary>
        public static string TimePage_Longitude {
            get {
                return ResourceManager.GetString("TimePage_Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分 的本地化字符串。
        /// </summary>
        public static string TimePage_Minute {
            get {
                return ResourceManager.GetString("TimePage_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 感光模式 的本地化字符串。
        /// </summary>
        public static string TimePage_PhotosensitiveMode {
            get {
                return ResourceManager.GetString("TimePage_PhotosensitiveMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通过感光元件自动调整颜色模式 的本地化字符串。
        /// </summary>
        public static string TimePage_PhotosensitiveModeSubtitle {
            get {
                return ResourceManager.GetString("TimePage_PhotosensitiveModeSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 位置： 的本地化字符串。
        /// </summary>
        public static string TimePage_Position {
            get {
                return ResourceManager.GetString("TimePage_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string TimePage_Save {
            get {
                return ResourceManager.GetString("TimePage_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日出日落模式 的本地化字符串。
        /// </summary>
        public static string TimePage_SunriseSunsetMode {
            get {
                return ResourceManager.GetString("TimePage_SunriseSunsetMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用 Windows 位置服务，获取设备所在位置的日出日落时间 的本地化字符串。
        /// </summary>
        public static string TimePage_SunriseSunsetModeSubtitle {
            get {
                return ResourceManager.GetString("TimePage_SunriseSunsetModeSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前版本为最新版本 的本地化字符串。
        /// </summary>
        public static string Update_Tip1 {
            get {
                return ResourceManager.GetString("Update_Tip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发现新版本 的本地化字符串。
        /// </summary>
        public static string Update_Tip2 {
            get {
                return ResourceManager.GetString("Update_Tip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接超时，请检查网络状态 的本地化字符串。
        /// </summary>
        public static string Update_Tip3 {
            get {
                return ResourceManager.GetString("Update_Tip3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动搜索 的本地化字符串。
        /// </summary>
        public static string WallpaperPage_AutoSearch {
            get {
                return ResourceManager.GetString("WallpaperPage_AutoSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浏览 的本地化字符串。
        /// </summary>
        public static string WallpaperPage_Browse {
            get {
                return ResourceManager.GetString("WallpaperPage_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 深色时 的本地化字符串。
        /// </summary>
        public static string WallpaperPage_Dark {
            get {
                return ResourceManager.GetString("WallpaperPage_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浅色时 的本地化字符串。
        /// </summary>
        public static string WallpaperPage_Light {
            get {
                return ResourceManager.GetString("WallpaperPage_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手动选择 的本地化字符串。
        /// </summary>
        public static string WallpaperPage_ManualSearch {
            get {
                return ResourceManager.GetString("WallpaperPage_ManualSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原生壁纸 的本地化字符串。
        /// </summary>
        public static string WallpaperPage_NativeWallpaper {
            get {
                return ResourceManager.GetString("WallpaperPage_NativeWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置后自动切换主题色时，原生壁纸也会随之切换 的本地化字符串。
        /// </summary>
        public static string WallpaperPage_NativeWallpaperSubtitle {
            get {
                return ResourceManager.GetString("WallpaperPage_NativeWallpaperSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string WallpaperPage_Save {
            get {
                return ResourceManager.GetString("WallpaperPage_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wallpaper Engine 壁纸 的本地化字符串。
        /// </summary>
        public static string WallpaperPage_WallpaperEngine {
            get {
                return ResourceManager.GetString("WallpaperPage_WallpaperEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 Wallpaper Engine 路径 的本地化字符串。
        /// </summary>
        public static string WallpaperPage_WallpaperEnginePath {
            get {
                return ResourceManager.GetString("WallpaperPage_WallpaperEnginePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置后自动切换主题色时，Wallpaper Engine 壁纸也会随之切换 的本地化字符串。
        /// </summary>
        public static string WallpaperPage_WallpaperEngineSubtitle {
            get {
                return ResourceManager.GetString("WallpaperPage_WallpaperEngineSubtitle", resourceCulture);
            }
        }
    }
}
